### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por id
GET http://localhost:3000/movies/9e6106f0-848b-4810-a11a-3d832a5610f9

### Recuperar todas las peliculas por un género
GET http://localhost:3000/movies?genre=terror

### Crear una pelicula con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "sql": "SELECT * from users",
  "title": "Halloween",
  "year": 2018,
  "director": "David Gordon Green",
  "duration": 105,
  "poster": "https://image.tmdb.org/t/p/original/l578Zg8oIyEJdfzGIw8iewUIxPk.jpg",
  "genre": [
      "Terror",
      "Thriller",
      "Slasher"
  ]
}

### Actualizar una pelicula
PATCH http://localhost:3000/movies/9e6106f0-848b-4810-a11a-3d832a5610f9
Content-Type: application/json

{
  "year": 2024
}

### Eliminar una pelicula
DELETE http://localhost:3000/movies/7e3fd5ab-60ff-4ae2-92b6-9597f0308d1